In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd

In [5]:
import numpy as np

In [ ]:
obj1 = pd.Series([5,6,3,4])
obj1

0    5
1    6
2    3
3    4
dtype: int64

In [ ]:
obj1[obj1>4]

0    5
1    6
dtype: int64

In [ ]:
obj1 = pd.Series([5,1,3,8,4],index=['a','b','c','d','e'])
obj1

a    5
b    1
c    3
d    8
e    4
dtype: int64

In [ ]:
obj1['a']

5

In [ ]:
obj1[['a','c','e']]

a    5
c    3
e    4
dtype: int64

In [ ]:
obj1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
np.exp(obj1)

a     148.413159
b       2.718282
c      20.085537
d    2980.957987
e      54.598150
dtype: float64

In [ ]:
my_dict = {'Shaxzod':19,'Ali':18,'Jahongir':20,'Rustam':19}
type(my_dict)

dict

In [ ]:
my_ser = pd.Series(my_dict)
type(my_ser)

pandas.core.series.Series

In [ ]:
my_ser

Shaxzod     19
Ali         18
Jahongir    20
Rustam      19
dtype: int64

In [ ]:
inds = ['Ali','Rustam','Jahongir','Shaxzod','Botir']
my_ser1 = pd.Series(my_ser,index=inds)

In [ ]:
my_ser.isnull

<bound method Series.isnull of Shaxzod     19
Ali         18
Jahongir    20
Rustam      19
dtype: int64>

In [ ]:
pd.isnull(my_ser1)

Ali         False
Rustam      False
Jahongir    False
Shaxzod     False
Botir        True
dtype: bool

In [ ]:
my_ser1

Ali         18.0
Rustam      19.0
Jahongir    20.0
Shaxzod     19.0
Botir        NaN
dtype: float64

In [ ]:
my_ser

Shaxzod     19
Ali         18
Jahongir    20
Rustam      19
dtype: int64

In [ ]:
my_ser + my_ser1

Ali         36.0
Botir        NaN
Jahongir    40.0
Rustam      38.0
Shaxzod     38.0
dtype: float64

In [ ]:
my_ser*my_ser1

Ali         324.0
Botir         NaN
Jahongir    400.0
Rustam      361.0
Shaxzod     361.0
dtype: float64

In [ ]:
my_ser2 = pd.Series(['Shaxzod','Rahmonov','talaba','dasturchi'],index=['ismi','familyasi','unvoni','kasbi'])
my_ser2

ismi           Shaxzod
familyasi     Rahmonov
unvoni          talaba
kasbi        dasturchi
dtype: object

In [ ]:
my_ser3 = pd.Series(['Nurik','Yarashabayev','talaba','dasturchi_AI'],index=['ismi','familyasi','unvoni','kasbi'])
my_ser3

ismi                Nurik
familyasi    Yarashabayev
unvoni             talaba
kasbi        dasturchi_AI
dtype: object

In [ ]:
my_ser4 = pd.Series(my_ser2,index=['familyasi','ismi','maoshi','unvoni','kasbi','staji'])
my_ser5 = pd.Series(my_ser3,index=['familyasi','ismi','maoshi','unvoni','kasbi','staji'])

In [ ]:
my_ser4

familyasi     Rahmonov
ismi           Shaxzod
maoshi             NaN
unvoni          talaba
kasbi        dasturchi
staji              NaN
dtype: object

In [ ]:
my_ser5

familyasi    Yarashabayev
ismi                Nurik
maoshi                NaN
unvoni             talaba
kasbi        dasturchi_AI
staji                 NaN
dtype: object

In [ ]:
my_ser4.name = "Shaxzodjon"

In [ ]:
my_ser4.index.name="atributlari"
my_ser4

atributlari
familyasi     Rahmonov
ismi           Shaxzod
maoshi             NaN
unvoni          talaba
kasbi        dasturchi
staji              NaN
Name: Shaxzodjon, dtype: object

In [ ]:
my_ser4['maoshi']=5000

In [ ]:
my_ser4

atributlari
familyasi     Rahmonov
ismi           Shaxzod
maoshi            5000
unvoni          talaba
kasbi        dasturchi
staji              NaN
Name: Shaxzodjon, dtype: object

In [ ]:
my_ser4+my_ser5

atributlari
familyasi     RahmonovYarashabayev
ismi                  ShaxzodNurik
maoshi                         NaN
unvoni                talabatalaba
kasbi        dasturchidasturchi_AI
staji                          NaN
dtype: object

In [ ]:
my_ser4.index

Index(['familyasi', 'ismi', 'maoshi', 'unvoni', 'kasbi', 'staji'], dtype='object', name='atributlari')

In [ ]:
my_ser4.values

array(['Rahmonov', 'Shaxzod', 5000, 'talaba', 'dasturchi', nan],
      dtype=object)

In [ ]:
pd.notnull(my_ser5)

familyasi     True
ismi          True
maoshi       False
unvoni        True
kasbi         True
staji        False
dtype: bool

In [ ]:
my_ser5

familyasi    Yarashabayev
ismi                Nurik
maoshi                NaN
unvoni             talaba
kasbi        dasturchi_AI
staji                 NaN
dtype: object

In [ ]:
my_ser5.hasnans

True

In [ ]:
my_ser5.is_unique

False

In [ ]:
my_ser5.shape

(6,)

In [ ]:
my_ser5.size

6

In [ ]:
my_ser5.iloc[3]

'talaba'

In [ ]:
my_ser5.loc['unvoni']

'talaba'

In [ ]:
my_ser5.max

<bound method NDFrame._add_numeric_operations.<locals>.max of familyasi    Yarashabayev
ismi                Nurik
maoshi                NaN
unvoni             talaba
kasbi        dasturchi_AI
staji                 NaN
dtype: object>

In [7]:
dataframe1 = pd.DataFrame({
    'ism':['Shaxzod','Rustamjon','Alisher','Muhammad','Nurgeldi'],
    'familya':['Rahmonov','Alijonov','Axmedov','Toshboltayev','Yarashbayev'],
    'yosh':[19,19,21,20,19],
    'qabul_turi':['grand','kantrakt','grand','kontrakt','grand']
})

In [8]:
dataframe1

ism       familya  yosh qabul_turi
0    Shaxzod      Rahmonov    19      grand
1  Rustamjon      Alijonov    19   kantrakt
2    Alisher       Axmedov    21      grand
3   Muhammad  Toshboltayev    20   kontrakt
4   Nurgeldi   Yarashbayev    19      grand

In [ ]:
dataframe1.head(2)

ism   familya  yosh qabul_turi
0    Shaxzod  Rahmonov    19      grand
1  Rustamjon  Alijonov    19   kantrakt

In [ ]:
dataframe1.ism

0      Shaxzod
1    Rustamjon
2      Alisher
3     Muhammad
4     Nurgeldi
Name: ism, dtype: object

In [9]:
ismlar = pd.Series(['Shaxzod','Rustamjon','Alisher','Muhammad','Nurgeldi'])
ismlar

0      Shaxzod
1    Rustamjon
2      Alisher
3     Muhammad
4     Nurgeldi
dtype: object

In [ ]:
dataframe1['ism'] = ismlar

In [ ]:
dataframe1

ism       familya  yosh qabul_turi
0    Shaxzod      Rahmonov    19      grand
1  Rustamjon      Alijonov    19   kantrakt
2    Alisher       Axmedov    21      grand
3   Muhammad  Toshboltayev    20   kontrakt
4   Nurgeldi   Yarashbayev    19      grand

In [ ]:
dataframe1['19+'] = dataframe1.yosh>19
dataframe1

ism       familya  yosh qabul_turi    19+
0    Shaxzod      Rahmonov    19      grand  False
1  Rustamjon      Alijonov    19   kantrakt  False
2    Alisher       Axmedov    21      grand   True
3   Muhammad  Toshboltayev    20   kontrakt   True
4   Nurgeldi   Yarashbayev    19      grand  False

In [10]:
data = {
    'ism':['Shaxzod','Rustamjon','Alisher','Muhammad','Nurgeldi'],
    'familya':['Rahmonov','Alijonov','Axmedov','Toshboltayev','Yarashbayev'],
    'yosh':[19,19,21,20,19],
    'qabul_turi':['grand','kantrakt','grand','kontrakt','grand']
}
dataframe2 = pd.DataFrame(data,columns=['ism','familya','yosh','qabul_turi','gpa'])

In [ ]:
dataframe2

ism       familya  yosh qabul_turi  gpa
0    Shaxzod      Rahmonov    19      grand  NaN
1  Rustamjon      Alijonov    19   kantrakt  NaN
2    Alisher       Axmedov    21      grand  NaN
3   Muhammad  Toshboltayev    20   kontrakt  NaN
4   Nurgeldi   Yarashbayev    19      grand  NaN

In [11]:
dataframe2 = pd.DataFrame(data,columns=['ism','familya','yosh','qabul_turi','gpa'],index=[11,12,13,14,15])

In [ ]:
dataframe2

ism       familya  yosh qabul_turi  gpa
11    Shaxzod      Rahmonov    19      grand  NaN
12  Rustamjon      Alijonov    19   kantrakt  NaN
13    Alisher       Axmedov    21      grand  NaN
14   Muhammad  Toshboltayev    20   kontrakt  NaN
15   Nurgeldi   Yarashbayev    19      grand  NaN

In [ ]:
gpaes = pd.DataFrame([4.5,4.2,3],index=[11,15,12])
dataframe2.gpa = gpaes

In [ ]:
dataframe2

ism       familya  yosh qabul_turi  gpa
11    Shaxzod      Rahmonov    19      grand  4.5
12  Rustamjon      Alijonov    19   kantrakt  3.0
13    Alisher       Axmedov    21      grand  NaN
14   Muhammad  Toshboltayev    20   kontrakt  NaN
15   Nurgeldi   Yarashbayev    19      grand  4.2

In [13]:
from pandas import *
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       "Temp":[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]}
df = DataFrame(data)

In [ ]:
df

Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [ ]:
arr = df.values

In [ ]:
arr

array([[2.021e+03, 3.390e+01, 1.540e+00],
       [2.020e+03, 3.350e+01, 1.480e+00],
       [2.019e+03, 3.290e+01, 1.560e+00],
       [2.018e+03, 3.250e+01, 1.620e+00],
       [2.017e+03, 3.190e+01, 1.650e+00],
       [2.016e+03, 3.140e+01, 1.660e+00],
       [2.015e+03, 3.090e+01, 1.640e+00],
       [2.010e+03, 2.850e+01, 1.530e+00]])

In [ ]:
df.head()

Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [19]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}


In [20]:
df = DataFrame(data)

In [21]:
df

Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [22]:
df.head()

Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1

2021  2020  2019  2018  2017  2016
Uzbekistan  33.9  33.5  32.9  32.5  31.9   NaN
Kazakhstan  18.9  18.7  18.5  18.3  18.1  17.8

In [ ]:
df.values

array([[33.9, 18.9],
       [33.5, 18.7],
       [32.9, 18.5],
       [32.5, 18.3],
       [31.9, 18.1],
       [ 0. , 17.8]])

In [23]:
df2 = DataFrame(data,index=[2021,2019,2017])
df2

Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [ ]:
2021 in df2.index

True

In [ ]:
df.index.insert(2,2030)

Int64Index([2021, 2020, 2030, 2019, 2018, 2017, 2016], dtype='int64')

In [24]:
indekslar = df2.columns
indekslar

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

In [28]:
indekslar[0]

'Uzbekistan'

In [31]:
usernames = {"anvar":"anvarbek223","olim":"olimtoy","maryam":"mary339","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com","olim":"oli@mail.ru","maryam":"mary339@gmail.com","javohir":"javohir34@gamil.com"}

data = {
    'username':usernames,
    'email':emails
}

In [32]:
df = DataFrame(data)
df

username                email
anvar    anvarbek223      anvar@gmail.com
olim         olimtoy          oli@mail.ru
maryam       mary339    mary339@gmail.com
javohir   javohir445  javohir34@gamil.com

In [33]:
idk = df.index
idk

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [35]:
df.columns

Index(['username', 'email'], dtype='object')

In [36]:
idk[0]

'anvar'

In [44]:
data2 = {
    'username':{"Shaxzod":"shaxzod2805","anvar":"anvarbek223"},
    'email':{"Shaxzod":"shaxzod28@gmail.com","anvar":"anvarbek2@gmail.com"}
}
df2 = DataFrame(data2)
df2

username                email
Shaxzod  shaxzod2805  shaxzod28@gmail.com
anvar    anvarbek223  anvarbek2@gmail.com

In [45]:
df2.index

Index(['Shaxzod', 'anvar'], dtype='object')

In [46]:
df3 = df.append(df2)
df3

username                email
anvar    anvarbek223      anvar@gmail.com
olim         olimtoy          oli@mail.ru
maryam       mary339    mary339@gmail.com
javohir   javohir445  javohir34@gamil.com
Shaxzod  shaxzod2805  shaxzod28@gmail.com
anvar    anvarbek223  anvarbek2@gmail.com

In [47]:
df3['Anvar']

KeyError: 'Anvar'

In [48]:
df3

username                email
anvar    anvarbek223      anvar@gmail.com
olim         olimtoy          oli@mail.ru
maryam       mary339    mary339@gmail.com
javohir   javohir445  javohir34@gamil.com
Shaxzod  shaxzod2805  shaxzod28@gmail.com
anvar    anvarbek223  anvarbek2@gmail.com

In [49]:
newind = pd.Index(['olim','rustam','Shaxzod'])
newind

Index(['olim', 'rustam', 'Shaxzod'], dtype='object')

In [50]:
newind.isin(df3.index)

array([ True, False,  True])

In [54]:
df3.index.difference(newind)

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [55]:
newind.difference(df3.index)

Index(['rustam'], dtype='object')

In [56]:
newind.union(df3.index)


Index(['Shaxzod', 'anvar', 'anvar', 'javohir', 'maryam', 'olim', 'rustam'], dtype='object')

In [57]:
newind.insert(2,'alijon')

Index(['olim', 'rustam', 'alijon', 'Shaxzod'], dtype='object')

In [58]:
newind.is_unique

True

In [60]:
df3.index.unique

<bound method Index.unique of Index(['anvar', 'olim', 'maryam', 'javohir', 'Shaxzod', 'anvar'], dtype='object')>

In [61]:
df3.index.is_monotonic

False